name: MineResetLite
version: 0.4.7
main: com.koletar.jj.mineresetlite.MineResetLite
author: Lyonix
authors: [jjKoletar, VirtualByte, TWWSYesterday, Boomclaw, veesayshi]
description: A lightweight solution for Mine management.
softdepend: [WorldEdit, Multiverse-Core, PrisonMines, Multiworld]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.